@startuml 

title Use Case Diagram

left to right direction


actor Administrator as adm

adm --> (Register backoffice users)
adm --> (Register patients)
adm --> (Edit a patients profile)
adm --> (Delete patients profile)
adm --> (List/Search patients profiles)
adm --> (Register staff)
adm --> (Edit a staff's profile)
adm --> (Deactivate a staff's profile)
adm --> (List/Search staff profiles)
adm --> (Add new operation types)
adm --> (Edit operation types)
adm --> (Remove operation types)
adm --> (List/Search operation types)

actor Doctor as dc

dc --> (Request an operation)
dc --> (Update an operation request)
dc --> (Remove an operation request)
dc --> (List/Search all operation requests)

actor Patient as pt

pt --> (Register into the healthcare application)
pt --> (Update their profile)
pt --> (Delete their profile)
pt --> (Log in)

actor BackofficeUser as bu

bu --> (Log in)
bu --> (Reset password)


@enduml