@startuml Generics

autonumber
skinparam packageStyle rect

title Create Resource

participant "Hospital" as H <<system (C4)>>

-> H: POST resources/{...}

activate H

alt resource Created

  <-- H: Response status code - 201

else invalid input

  <-- H: Response status code - 400

else unauthorized

  <-- H: Response status code - 401

else necessary resource not found

  <-- H: Response status code - 404

else resource already exists

  <-- H: Response status code - 409

else database unavailable

  <-- H: Response status code - 503

else database error

  <-- H: Response status code - 500

end

@enduml