@startuml Process View - Level 2

autonumber
skinparam packageStyle rect

title Delete {Resources}

actor "User" as U <<DEI User>>
participant "PortalModule" as RPM <<component>>
participant "BackOfficeModule" as DAM <<component>>

activate U

U -> RPM:  Asks to delete {Resources}

activate RPM

U <-- RPM: Asks the user to select the {Resources} to delete

U -> RPM:  Selects the {Resources} to delete

RPM -> DAM: DELETE resources/{...}

activate DAM
alt success
RPM <-- DAM: Response status code - 200

alt
U <-- RPM: display deleted {Resources} message
else no resources available
U <-- RPM: display not deleted {Resources} message
end

else unsuccessful

alt entity not found
 RPM <-- DAM: Response status code - 404
else database unavailable
 RPM <-- DAM: Response status code - 503
deactivate DAM
end
 U<-- RPM: display error message


deactivate RPM
end
deactivate U

@enduml